Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  # TUN/TAP сервер
  config.vm.define "tun-tap-server" do |server|
    server.vm.hostname = "tun-tap-server"
    server.vm.network "private_network", ip: "192.168.56.10"
  end

  # TUN/TAP клиент
  config.vm.define "tun-tap-client" do |client|
    client.vm.hostname = "tun-tap-client" 
    client.vm.network "private_network", ip: "192.168.56.20"
  end

  # Базовый провижининг
  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y epel-release
    dnf install -y openvpn iperf3 net-tools iproute tcpdump
    systemctl stop firewalld
    systemctl disable firewalld
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
    sysctl -p
  SHELL
end
