---
- name: Install rsyslog
  dnf:
    name: rsyslog
    state: present

- name: Configure rsyslog for remote logging
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    backup: yes
  notify: restart rsyslog

- name: Ensure rsyslog is running
  systemd:
    name: rsyslog
    state: started
    enabled: yes
