Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  # Master node
  config.vm.define "master" do |master|
    master.vm.box = "generic/rocky9"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.150"
    master.vm.synced_folder ".", "/vagrant", type: "rsync"
    
    master.vm.provision "shell", path: "scripts/master.sh"
  end

  # Slave node
  config.vm.define "slave" do |slave|
    slave.vm.box = "generic/rocky9"
    slave.vm.hostname = "slave"
    slave.vm.network "private_network", ip: "192.168.56.151"
    slave.vm.synced_folder ".", "/vagrant", type: "rsync"
    
    slave.vm.provision "shell", path: "scripts/slave.sh"
  end
end
