network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:  # office2-central
      addresses:
      - 192.168.255.6/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.5
      - to: 192.168.0.0/24
        via: 192.168.255.5
      - to: 192.168.2.0/24
        via: 192.168.255.5
    enp2s0:  # dev2-net
      addresses:
      - 192.168.1.1/25
    enp3s0:  # test2-net
      addresses:
      - 192.168.1.129/26
    enp4s0:  # office2-net
      addresses:
      - 192.168.1.193/26
    enp7s0:  # management
      addresses:
      - 192.168.50.30/24
