network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:  # router-net
      addresses:
      - 192.168.255.2/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.1
    enp2s0:  # dir-net
      addresses:
      - 192.168.0.1/28
    enp3s0:  # hw-net
      addresses:
      - 192.168.0.33/28
    enp4s0:  # mgt-net
      addresses:
      - 192.168.0.65/26
    enp5s0:  # office1-central
      addresses:
      - 192.168.255.9/30
      routes:
      - to: 192.168.2.0/24
        via: 192.168.255.10
    enp6s0:  # office2-central
      addresses:
      - 192.168.255.5/30
      routes:
      - to: 192.168.1.0/24
        via: 192.168.255.6
    enp7s0:  # management
      addresses:
      - 192.168.50.11/24
