network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:  # dir-net
      addresses:
      - 192.168.0.2/28
      routes:
      - to: 0.0.0.0/0
        via: 192.168.0.1
    enp7s0:  # management
      addresses:
      - 192.168.50.12/24
