---
- name: Configure OSPF networks
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install basic tools
      dnf:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
          - wget
        state: present

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure network interfaces via nmcli
      nmcli:
        conn_name: "{{ item.name }}"
        ifname: "{{ item.interface }}"
        type: ethernet
        ip4: "{{ item.ip }}/{{ item.prefix }}"
        state: present
      loop:
        - { name: "r1-r2", interface: "eth1", ip: "10.0.10.1", prefix: "30" }
        - { name: "r1-r3", interface: "eth2", ip: "10.0.12.1", prefix: "30" }
        - { name: "net1", interface: "eth3", ip: "192.168.10.1", prefix: "24" }
      when: inventory_hostname == 'router1'

    - name: Configure network interfaces for router2
      nmcli:
        conn_name: "{{ item.name }}"
        ifname: "{{ item.interface }}"
        type: ethernet
        ip4: "{{ item.ip }}/{{ item.prefix }}"
        state: present
      loop:
        - { name: "r1-r2", interface: "eth1", ip: "10.0.10.2", prefix: "30" }
        - { name: "r2-r3", interface: "eth2", ip: "10.0.11.2", prefix: "30" }
        - { name: "net2", interface: "eth3", ip: "192.168.20.1", prefix: "24" }
      when: inventory_hostname == 'router2'

    - name: Configure network interfaces for router3
      nmcli:
        conn_name: "{{ item.name }}"
        ifname: "{{ item.interface }}"
        type: ethernet
        ip4: "{{ item.ip }}/{{ item.prefix }}"
        state: present
      loop:
        - { name: "r2-r3", interface: "eth1", ip: "10.0.11.1", prefix: "30" }
        - { name: "r1-r3", interface: "eth2", ip: "10.0.12.2", prefix: "30" }
        - { name: "net3", interface: "eth3", ip: "192.168.30.1", prefix: "24" }
      when: inventory_hostname == 'router3'
