Vagrant.configure("2") do |config|
  # Используем последнюю версию centos/stream9
  config.vm.box = "centos/stream9"
  
  # Router1
  config.vm.define "router1" do |router1|
    router1.vm.hostname = "router1"
    router1.vm.network "private_network", ip: "192.168.50.10"
  end

  # Router2
  config.vm.define "router2" do |router2|
    router2.vm.hostname = "router2"
    router2.vm.network "private_network", ip: "192.168.50.11"
  end

  # Router3
  config.vm.define "router3" do |router3|
    router3.vm.hostname = "router3"
    router3.vm.network "private_network", ip: "192.168.50.12"
  end
end
