---
- name: Install EPEL repository
  dnf:
    name: epel-release
    state: present

- name: Install required packages
  dnf:
    name:
      - borgbackup
      - openssh-server
      - python3
    state: present

- name: Create borg user
  user:
    name: borg
    shell: /bin/bash
    home: /home/borg
    system: yes
    create_home: yes
    password: "{{ 'vagrant' | password_hash('sha512') }}"

- name: Fix borg user home directory permissions
  file:
    path: /home/borg
    owner: borg
    group: borg
    mode: '0700'
    state: directory

- name: Create .ssh directory for borg user
  file:
    path: /home/borg/.ssh
    state: directory
    owner: borg
    group: borg
    mode: '0700'

- name: Create authorized_keys file
  file:
    path: /home/borg/.ssh/authorized_keys
    state: touch
    owner: borg
    group: borg
    mode: '0600'

- name: Create backup directory
  file:
    path: /var/backup
    state: directory
    owner: borg
    group: borg
    mode: '0755'

- name: Ensure SSH service is started and enabled
  systemd:
    name: sshd
    state: started
    enabled: yes

#- name: Restart SSH service to apply changes
#  systemd:
#    name: sshd
#    state: restarted

