# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  # PXE Server
  config.vm.define "pxeserver" do |server|
    server.vm.hostname = "pxeserver"
    
    # Internal network for PXE
    server.vm.network "private_network", 
      ip: "10.0.0.20",
      virtualbox__intnet: "pxenet"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "pxeserver"
    end
    
    # Ansible provisioning
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      ansible.inventory_path = "ansible/hosts"
      ansible.host_key_checking = false
      ansible.become = true
    end
  end

  # PXE Client
  config.vm.define "pxeclient" do |client|
    client.vm.hostname = "pxeclient"
    
    # Connect to PXE network
    client.vm.network "private_network", 
      virtualbox__intnet: "pxenet"
    
    client.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.name = "pxeclient"
      
      # Configure network boot
      vb.customize [
        "modifyvm", :id,
        "--nic1", "intnet",
        "--intnet1", "pxenet", 
        "--nictype1", "virtio",
        "--boot1", "net",
        "--boot2", "disk",
        "--boot3", "none",
        "--boot4", "none"
      ]
    end
  end
end
